- .gitignore
- Dockerfile.build
Signed-off-by: Lisa Rashidi-Ranjbar <lisa.a.rashidi-ranjbar@intel.com>
> Update golang to 1.12 in local build

- README.md
- bootstrap/handlers/httpserver/httpserver.go
- bootstrap/handlers/message/message.go
- bootstrap/handlers/secret/secret.go
- config/types.go
> Minor code/README.md clean up

- bootstrap/handlers/httpserver/httpserver.go
- bootstrap/handlers/message/message.go
- bootstrap/handlers/secret/credentials.go
Fixes: https://github.com/edgexfoundry/go-mod-bootstrap/issues/24
> Bootstrap Factory Functions should return references

- bootstrap/bootstrap.go
- bootstrap/handlers/testing/ready.go
Fixes: https://github.com/edgexfoundry/go-mod-bootstrap/issues/27
> Update to support Golang-based acceptance testing

- bootstrap/handlers/httpserver/httpserver.go
Fixes: https://github.com/edgexfoundry/go-mod-bootstrap/issues/29
> Modify HttpServer bootstrap to not ListenAndServe when running acceptance tests

- bootstrap/bootstrap.go
- bootstrap/config/config.go
Issue Number: https://github.com/edgexfoundry/go-mod-bootstrap/issues/46
When provided, a stream passed to RunAndReturnWaitGroup() is called when a configuration provider is used and a remote configuration change is made.
Dependent upon https://github.com/edgexfoundry/go-mod-bootstrap/issues/44
> Add ability to notify bootstrap consumer of config update

- bootstrap/bootstrap.go
Fixes: https://github.com/edgexfoundry/go-mod-bootstrap/issues/49
Issue Number: https://github.com/edgexfoundry/go-mod-bootstrap/issues/49
Changes contract for RunAndReturnWaitGroup().
> Services using registry are immediately unregistered with the registry

- config/types.go
Fix #56 
Consul client can't fetch the username and password with Credentials inner struct. 
Issue Number: #56 
Flattening the Database data structure to fetch the username and password.
> Flattening the Database data structure.

- bootstrap/config/config.go
Code trying to receive from an UpdatedStream will not compile 
Issue Number: #65 
Code now compiles.
> fix(config): Change UpdatedStream to be defined as `chan struct{}`

- bootstrap/handlers/secret/credentials.go
Signed-off-by: Andre Srinivasan <andre.srinivasan@gmail.com>
- [N/A ] Tests for the changes have been added (for bug fixes / features)
- [N/A] Docs have been added / updated (for bug fixes / features)
Allow microservices configured for Redis to retrieve DB password from vault
Microservices cannot get the Redis password from Vault
Issue Number: #67
> Allow microservices configured for Redis to retrieve DB password from vault

- bootstrap/config/environment.go
- bootstrap/config/environment_test.go
Environment variable override names have to be exact case used in TOML file.
Issue Number:  #69
Environment variable override names can now be uppercase or an case
> feat(environment): Perform case insensitive comparison for config override names

- bootstrap/config/config.go
First notification of config changes on start-up doesn't contain any changes, but causes issues with overrides that were just applied.
Issue Number: #72
First notification of config changes on start-up are now skipped
> Fix: Ignore first config changes notification on start-up

- config/types.go
Active client monitoring has be removed, so the ClientMonitor interval setting is no longer needed.
Issue Number:  #80
ClientMonitor interval setting removed from ServiceInfo struct
No
> refactor(config): Remove ClientMonitor from the ServiceInfo struct

- Dockerfile.build
- Jenkinsfile
- README.md
- go.mod
Updated Dockerfile, go.mod for Go 1.15
Removed go reference in Jenkinsfile so it defaults to CI/CD pipeline default
Updated README Go version references
Fixes: #87
Signed-off-by: Jim White <jpwhite_mn@yahoo.com>
- [ x] Build related changes
- [x ] Other... Please describe: upgrade to Go 1.15
n/a
Issue Number: #87 
none
> fix(build): update to go 1.15

- go.mod
Issue Number:  #89
go.mod is up to date with respect to the dependent edgex go-mods.
no
> build: Update dependent go-mod versions

- bootstrap/bootstrap.go
- bootstrap/config/config.go
- bootstrap/config/provider.go
- bootstrap/config/provider_test.go
- bootstrap/container/cancel.go
- bootstrap/environment/variables.go
- bootstrap/environment/variables_test.go
- bootstrap/flags/flags.go
- bootstrap/flags/flags_test.go
- bootstrap/handlers/httpserver.go
- bootstrap/registration/registry.go
- bootstrap/registration/registry_test.go
Existing code has many backward compatibility code blocks
Backward compatibility code blocks have been removed
> refactor: Remove backward compatibility code

- bootstrap/config/config.go
LogLevel is not being set to configured level
LogLevel is now being set to configured level
> fix: Add setting the configured LogLevel

- bootstrap/handlers/secret.go
- bootstrap/handlers/secret_test.go
- config/types.go
- go.mod
used previous verion of go-mod-secrets
Uses latest version of go-mod-secrets
Adjusted for renamed client and addition of `Type` in Secret Store configuration
Dependent on PR https://github.com/edgexfoundry/go-mod-secrets/pull/91 to be merged
BREAKING CHANGE: All existing SecretStore configuration must add Type = 'vault'
> refactor: Update to latest go-mod-secrets

- bootstrap/config/config.go
Overwrite capability is NOT supported for custom configuration.
Overwrite capability is supported for custom configuration.
>  feat: Add overwrite capability for custom configuration

- bootstrap/config/config.go
Use of channel causes too much unneeded complexity for caller.
Uses callback function instead of channel
> refactor: Refactor ListenForCustomConfigChanges to avoid use of channel

- bootstrap/config/config.go
Config Version constant not exposed
Config Version constant now exposed for services to use if needed.
> refactor: Expose ConfigVersion so services can use if needed

- bootstrap/interfaces/mocks/SecretProvider.go
SecretProvider  mock is out of date
SecretProvider  mock is up to date
> fix: Generate mock for latest SecretProvider interface

- Dockerfile.build
- README.md
- go.mod
update go.mod, Dockerfile.build, README.md
Signed-off-by: Jim White <jpwhite_mn@yahoo.com>
upgrade Go Lang to 1.16
> build: upgrade Go lang to 1.16

- config/types.go
Close #239
Add SubscribeEnabled config to MessageQueue config
> feat: Add Subscribe config to MessageQueue config

- bootstrap/handlers/httpserver.go
Error message is log when there isn't an error. When the is an error the handler still returns true.
Error message is only logged when there is an error and hander returns false on error.
> fix: Add conditional for error message and return false on error

- go.mod
Using 2.0 dev versions of go-mods
Now using release 2.0/0 versions of go-mods
- [ x No
> build: Update to all the released go-mods

- .github/PULL_REQUEST_TEMPLATE.md
Updated the PR template to the newly approved template.
> ci: Update PR template to new recently approved template

- README.md
- go.mod
- go.sum
Changes related to Go 1.17 module changes
> ci: gomod changes related for Go 1.17

- go.mod
- go.sum
Closes: #316
- [x ] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x ] I am not introducing a new dependency (add notes below if you are)
> feat(security): Use go-mod-secrets version that includes the capability of using non_delayedstart go build tags

- bootstrap/metrics/reporter.go
- bootstrap/metrics/reporter_test.go
> refactor: Rework the reported Metric field names to be more meaningful

- Makefile
- bootstrap/handlers/metrics.go
> fix: resolves issue #332

- go.mod
- go.sum
- vendor/github.com/edgexfoundry/go-mod-core-contracts/v2/dtos/address.go
- vendor/modules.txt
> build: Update to released 2.1.1 Go Mods

- bootstrap/metrics/reporter.go
- bootstrap/metrics/reporter_test.go
> feat: Add Histogram to supported metric types

- config/types.go
Signed-off-by: Chris Hung <chris@iotechsys.com>
fix #377 
> feat: add 'Enabled' field in ExternalMQTTInfo

- bootstrap/bootstrap.go
> fix: Don't run general service metrics code for security bootstrap services

- go.mod
- go.sum
> build: Latest go-mods

- bootstrap/handlers/messaging.go
- go.mod
- go.sum
This PR is dependent on https://github.com/edgexfoundry/go-mod-messaging/pull/200
Run non-secure edgex stack and stop core data
Build core data with this branch and branch from https://github.com/edgexfoundry/go-mod-messaging/pull/200
Run local core data with DEBUG logging
Verify Core data logs show events received from MessageBus
> refactor: Adjust to MessageBus config with single broker host info

- go.mod
- go.sum
Signed-off-by: Bryon Nevis <bryon.nevis@intel.com>
Unblocks #412
> build(deps): bump github.com/edgexfoundry/go-mod-messaging/v3

- go.mod
- go.sum
Signed-off-by: Lenny Goodell <leonard.goodell@intel.com>
> build: Update to latest Go Mods

- bootstrap/config/config.go
Signed-off-by: Elizabeth J Lee <elizabeth.j.lee@intel.com>
> refactor: config processor createProviderClient from receiver to helper

- bootstrap/handlers/clients.go
- bootstrap/handlers/clients_test.go
- bootstrap/handlers/messaging.go
- bootstrap/handlers/messaging_test.go
- bootstrap/handlers/metrics.go
- bootstrap/handlers/metrics_test.go
- bootstrap/metrics/reporter.go
- bootstrap/metrics/reporter_test.go
- config/types.go
- go.mod
- go.sum
BREAKING CHANGE: Topics no longer in configuration
TBD
> refactor!: Replace topics from config with new constants

- Makefile
- bootstrap/interfaces/metrics.go
- bootstrap/metrics/manager.go
> feat: implement IsRegistered to metrics manager

- go.mod
- go.sum
> fix: Consume MessageBus Request fix

- bootstrap/messaging/messaging.go
Closes #352
Checked that the constants are not in use in app-functions-sdk-go and go-mod-bootstrap.
It is possible that other modules MAY use these constants, and will have to make a decision then,
perhaps reverting this change.
> fix!: Remove unused AuthModeKey and SecretNameKey

- bootstrap/config/config.go
- bootstrap/config/config_test.go
- bootstrap/environment/variables.go
- bootstrap/environment/variables_test.go
- bootstrap/utils/utils.go
- bootstrap/utils/utils_test.go
- go.mod
- go.sum
BREAKING CHANGE: OverrideTomlValues changed to OverrideConfigMapValues
See [edgex-go PR](https://github.com/edgexfoundry/edgex-go/pull/4468) testing instructions
> refactor!: Rework to remove use of TOML package

- bootstrap/handlers/externalmqtt.go
- config/types.go
fix: #550 
https://github.com/edgexfoundry/edgex-docs/pull/1095
> fix: Rename SecretPath to SecretName

- go.mod
- go.sum
> chore(security): Bump go-mod-secrets

- bootstrap/file/file_test.go
closes #590
run unit tests for go-mod-bootstrap `make test` - all tests should pass.
> test: Add httpserver test for uri4files to check secret header

- go.mod
- go.sum
> build: Update to latest core contracts

- bootstrap/handlers/httpserver.go
> feat: respect when the timeout times out

- bootstrap/bootstrap.go
- bootstrap/registration/registry.go
> fix: Fixed regression bug of keeper clients with zero trust

- bootstrap/config/config.go
- bootstrap/environment/variables.go
Close https://github.com/edgexfoundry/go-mod-bootstrap/issues/747
https://github.com/edgexfoundry/edgex-docs/pull/1366
> fix: The env should override flags

- bootstrap/container/clients.go
- bootstrap/handlers/clients.go
- bootstrap/handlers/clients_test.go
> feat: Add Cron Scheduler Clients in ClientsBootstrap Handler

- bootstrap/file/file_test.go
> fix: Remove consul dependency unit test errors

- bootstrap/secret/secure.go
- bootstrap/secret/secure_test.go
> feat: Add EDGEX_USE_COMMON_APP_SERVICE_SECRET_KEY for service key overwrite

- bootstrap/config/config.go
- go.mod
- go.sum
> feat: Passing callback func to get message client in WatchForChanges

- bootstrap/metrics/reporter.go
- bootstrap/metrics/reporter_test.go
- go.mod
- go.sum
relate to: https://github.com/edgexfoundry/go-mod-messaging/issues/381
> feat: Update to use go-mod-messaging updated Msgenvelope functions

- bootstrap/handlers/httpserver.go
> feat: Make the timeout middleware optional

- bootstrap/config/config.go
> refactor: Replace MergeValues with full reload in applyWritableUpdates

- bootstrap/config/config.go
fix: #879 
- Load common configuration if raw is nil to init previousCommonWritable
- Store previousCommonWritable as map to avoid pointer reference syncing with Config Provider
1. Build device-virtual using this version of go-mod-bootstrap
2. Deploy core services and device-virtual
3. Use Core Keeper API to update a common writable configuration key. For example:
```
curl -X PUT http://localhost:59890/api/v3/kvs/key/edgex/v4/core-common-config-bootstrapper/all-services/Writable/Telemetry/Interval \
-H "Content-Type: application/json" \
-d '{"value": "20s"}'
```
4. The first config update should succeed and output this log:
```
level=INFO ts=2025-07-04T16:02:11.242333+08:00 app=device-virtual …
```
> fix: Handle nil raw config on first common writable config update

- config/types.go
Add Postgres ConnPool Config for user to tune the ConnPool.
> feat: Add Postgres ConnPool Config
