config/types.go
Fixes: https://github.com/edgexfoundry/go-mod-bootstrap/issues/3
=> Add missing ServiceInfo implementation

.gitignore, bootstrap/bootstrap.go, bootstrap/configuration/registry.go, bootstrap/handlers/httpserver/httpserver.go, bootstrap/handlers/message/message.go, bootstrap/handlers/secret/secret.go
Fix #16
Rename all non-global variable names from 'loggingClient' to 'lc'.
Update .gitignore to exclude common Go and IDE files.
Signed-off-by: Anthony M. Bonafide <AnthonyMBonafide@gmail.com>
=> Rename non-global variables loggingClient to lc

bootstrap/handlers/secret/credentials.go
Reverted change to GetDatabaseCredentials.
Fixes: https://github.com/edgexfoundry/go-mod-bootstrap/issues/24
=> Bootstrap Factory Functions should return references

go.mod
Fixes: https://github.com/edgexfoundry/go-mod-bootstrap/issues/31
=> Update to latest (v0.0.13) go-mod-secrets

config/types.go
Replaced embedded type vault.SecretConfig with copy of the fields from the type.
closes #37
=> bug(config): Embedded types do not work with package we use to pull from Consul

bootstrap/bootstrap.go, go.mod
Issue Number: https://github.com/edgexfoundry/go-mod-bootstrap/issues/41
Adds new RunAndReturnWaitGroup() function.  Returns immediately instead of waiting on a sync.WaitGroup for the service to end.  New method intended to facilitate adoption of go-mod-bootstrap by AppFunc (and possibly device service) subdomain.
Existing Run() method kept intact for backward-compatible usage by core-services, support-services, and system management agent.
Minor code reformatting.  Minor comment updates.
=> Add RunAndReturnWaitGroup() to bootstrap.go

Dockerfile.build, Jenkinsfile, go.mod
=> build: Update relevant files in go-mod-bootstrap for Go 1.13.

bootstrap/handlers/secret/client/mockserver_test.go, bootstrap/handlers/secret/client/testdata/replacement.json, bootstrap/handlers/secret/client/testdata/testToken.json, bootstrap/handlers/secret/client/vaultclient.go, bootstrap/handlers/secret/client/vaultclient_test.go, bootstrap/handlers/secret/secret.go, go.mod
Update the constructor of vault.NewSecretClient to use the latest go-mod-secrets version `v0.0.15`
- unit tests added for token expired call back cases
- refactor to use the vault secret client into its package client under package secret
The real code changes are minimal with quite some unit testing code introduced.
Fixes issue #35
The signature of `NewSecretClient()` of go-mod-secrets from older version (v0.0.14 and below) has been changed in version v0.0.15.  Currently code in `NewSecretClient()` no longer works for using version v0.0.15.
Issue Number:
#35 
In version `v0.0.15` of go-mod-secrets, the constructor to get …
=> Update the secret's BootstrapHandler to use the latest NewSecretClient

go.mod
The version `v0.0.15` of go-mod-secrets has the defect described in https://github.com/edgexfoundry/go-mod-secrets/issues/49 in that the API URL was not correctly built while looking up the Vault token.
This update to the version `v0.0.017` fixes this issue.
Closes: #52 
The version `v0.0.15` of go-mod-secrets has the defect described in https://github.com/edgexfoundry/go-mod-secrets/issues/49 in that the API URL was not correctly built while looking up the Vault token, which would result in status code 403.
Issue Number: #52 
The new version 0.0.17 should fix the issue on looking up the token when the NewSecretClient is called.
=> Update go.mod to use go-mod-secrets version v0.0.17

bootstrap/handlers/secret/secret.go
Address a race condition where the container may be started before
security-secrets-setup has created the secrets token for the service.
Signed-off-by: Bryon Nevis <bryon.nevis@intel.com>
When user performs
```sh
docker-compose -f docker-compose-blah.yml up -d
````
A number of core services such as support-logging, core-metadata, core-data, and others will fail to start with a message:
```
level=ERROR ts=2020-03-20T16:33:16.413174639Z app=edgex-core-command source=secret.go:67 msg="unable to create SecretClient: HTTP response with status code 403, message: failed to lookup token"
```
Issue Number:
- https://github.com/edgexfoundry/developer-scripts/issues/230
- …
=> fix: Add retry loop for secret client if initial token is invalid

bootstrap/config/config.go
Changed config.Processor reciever to be a pointer so the change to logger is propagated to caller.
closes #61
Signed-off-by: lenny <leonard.goodell@intel.com>
Logger not configured properly after processing the configuration.
Issue Number: #61 
Logger now properly configure per the processed configuration
=> fix(logging): Logger not configured properly

bootstrap/logging/factory.go
Fix #63
Signed-off-by: Trevor Conn <trevor_conn@dell.com>
- [ X] The commit message follows our guidelines: https://wiki.edgexfoundry.org/display/FA/Contributor%27s+Guide
- [X ] Bugfix
Issue Number: 63
Elminated unnecessary log entry when LogFile is blank in configuration 
- [X ] No
=> Eliminate erroneous log msg when LogFile path is blank

bootstrap/config/environment.go, bootstrap/config/environment_test.go
Env overrides with blank values such as Service_Host="" were ignored.
Issue Number: #74 
Env overrides with blank values no work.
=> fix: Allow overrides that have empty/blank value

bootstrap/handlers/httpserver/httpserver.go
Issue Number: #76
ListenAndServe was lock to specific adapter for the specified hostname 
ListenAndServe now not using hostname so available on any of the host system's adapters
=> fix: Don't use hostname for webserver ListenAndServe

bootstrap/handlers/httpserver/httpserver.go, config/types.go
The `ListenAndServe` IP address defaults to binding to an all-interface listener value of `0.0.0.0`.
Issue Number: #83 
This change adds a `ServerBindAddr` configurable value. (This name is up for debate, if others have input feel free)
No
No
N/A
=> fix: configurable ip address for ListenAndServe, fixes #83

bootstrap/bootstrap.go, bootstrap/config/config.go, bootstrap/config/provider.go, bootstrap/config/provider_test.go, bootstrap/environment/variables.go, bootstrap/environment/variables_test.go, bootstrap/interfaces/configuration.go, bootstrap/logging/factory.go, bootstrap/registration/registry.go, bootstrap/registration/registry_test.go, bootstrap/startup/timer.go, config/types.go
Changing the Startup configuration has no impact and neither does using the startup env variables.  
The Startup configuration is not useful as it is needed prior to loading the configuration. 
Update of timer with values from Env Vars doesn't work.
Issue Number: #85
Service Startup config is not loaded when timer is created/updated so have been removed.
NewStartUpTimer now checks and uses Env values form start so update of timer no longer needed.
Startup configuration never worked, so removing it will is not a breaking change
No
Code restructuring was required to avoid circular imports
Requires changes to each service for the change in signature of NewStartUpTimer
=> fix: Startup Duration and Interval never updated from default values

bootstrap/environment/variables.go
The default startup duration of 30 seconds is not sufficient for low resource systems.
Issue Number:  #98
Default startup is now 60 seconds which has be proven to work for some low resource systems.
=> fix: Increase default startup duration to 60 seconds

bootstrap/environment/variables.go, bootstrap/environment/variables_test.go
**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-examples/blob/master/.github/CONTRIBUTING.md.
Env overrides values which have `=` in them are chopped off to have just the string before the `=`.
Env overrides values which have `=` in them are kept in tact.
Are there any new imports or modules? If so, what are they used for and why?
no
=> fix: Handle env override values which have the '=' character

.gitignore, bootstrap/flags/flags.go, bootstrap/flags/flags_test.go
Signed-off-by: André Srinivasan <andre@redislabs.com>
When an argument list contains a substring with _-r_ it is treated as the `-registry` flag. For example
```
service -configdir /foo/ba-r/
```
The _-r_ in _ba-r_ is seen as the `-registry` flag
Resolves #78 
Explicitly check for the regexp `^-(cp|configProvider)` and `^-(r|registry)`
Output `go test -v` before code changes
```
=== RUN   TestNewAllFlags
--- PASS: TestNewAllFlags (0.00s)
=== RUN   TestNewDefaultsNoFlags
--- PASS: TestNewDefaultsNoFlags (0.00s)
=== RUN …
```
=> fix: Accept argument lists with a -r substring

bootstrap/bootstrap.go, di/container.go, di/container_test.go, go.mod
Initial Logging client created by boot-strap uses DEBUG level and can not be overridden. This client is used until configuration is loaded.
Service can now pass an initial Logging Client in the DIC for bootstrap to use instead of creating one.
This enables Security Utility to run in silent mode as initial client can be set to EROOR instead of DEBUG as it now.
=> feat: Allow service to pass in initial logging client

bootstrap/container/logging.go
Commit 3651de7 revised bootstrap.go to DI get the logging client first as opposed to directly creating a Stdout logging client. However, the logic inside `LoggingClientFrom` doesn't deal with nil case and will result in `panic: interface conversion: interface is nil, not logger.LoggingClient`.
#128 
Deal with nil case inside `LoggingClientFrom` to avoid panic.
=> fix: LoggingClientFrom handle nil case properly

bootstrap/startup/timer.go
Time is specifically design for use during bootstrapping 
Time now has new factory method that allows it to be used for timed loop beyond bootstrapping.
Also added function to return time left on the time.
=> feat: Enhance Timer to be used for timed loops beyond bootstrapping

bootstrap/bootstrap.go, bootstrap/config/config.go, bootstrap/config/provider.go, bootstrap/config/provider_test.go, bootstrap/container/logging.go, bootstrap/container/registry.go, bootstrap/container/token.go, bootstrap/environment/variables.go, bootstrap/environment/variables_test.go, bootstrap/handlers/secret.go, bootstrap/handlers/secret_test.go, bootstrap/registration/registry.go, bootstrap/registration/registry_test.go, bootstrap/secret/insecure.go, bootstrap/secret/insecure_test.go, bootstrap/secret/secure.go, bootstrap/secret/secure_test.go, config/types.go, go.mod
Consuming V0 Go module versions for the edgeX go-mods
Consumes V2 Go module versions for the edgeX go-mods
=> refactor: Consume V2 Go Modules for edgex go-mods

go.mod, v2/bootstrap/container/deviceservice.go
Signed-off-by: Jude Hung <jude@iotechsys.com>
fix #161 
DeviceServiceCommandClient was added into go-mod-core-contracts, and we shall have corresponding helper function in go-mod-bootstrap to query DIC and then return the DeviceServiceCommandClient instance
=> feat(v2): Add helper to query DIC and returns the DeviceServiceCommandClient instance

bootstrap/config/config.go, bootstrap/container/configuration.go
Reference to the configuration client is not in the DIC.
Reference to the configuration client is now in the DIC where App Services can use it for custom config.
=> feat: Add config client in DIC

config/types.go
V1 Ping used for Consul health checks 
V2 Ping used for Consul health checks 
=> fix: Use V2 Ping for health check

bootstrap/config/config.go, bootstrap/registration/registry.go, bootstrap/token/token.go, bootstrap/token/token_test.go, config/types.go, go.mod
No support for Registry/Config access tokens
Registry/Config access token now enabled. and used if file path is set and the token file exists
=> feat: Enable use of Registry & Config client access token

bootstrap/registration/registry.go
Health checks still using `api/v1/ping`
Health checks now using `api/v2/ping`
=> fix: Use /api/v2/ping for Registry healthchecks

bootstrap/config/config.go
closes #200
Signed-off-by: lenny <leonard.goodell@intel.com>
Config version set separately by Core/Support, App and Device services.
This centralizes the config version for all Go services.
BREAKING CHANGE: Configuration in Consul now under the `/2.0/` path
=> refactor: Set the Config Version when creating Config Client

bootstrap/config/config.go, go.mod
Unmaintained module `BurntSushi/toml` is used to un-marshal TOML file
pelletier/go-toml module is now used to un-marshal TOML file
=> refactor: Replace use of BurntSushi/toml with pelletier/go-toml

bootstrap/secret/secure.go, bootstrap/secret/secure_test.go, go.mod
the API for calling GenerateConsulToken has changed from go-mod-secret and thus requires a change
Fixes: #211
interface changed
updated according to interface change
- [x ] No
- [x ] No
=> refactor: update calling GenerateConsulToken

bootstrap/messaging/messaging.go, bootstrap/messaging/messaging_test.go
username & password **can not** be blank in non-secure mode.
username & password **can now** be blank in non-secure mode.
=> fix: Fix Secure MessageBus Secret validation for non-secure mode

bootstrap/environment/variables.go, bootstrap/environment/variables_test.go
Hyphens accepted on override names
Hyphen is not a standard character for environment variable names
Hyphens are replaced with underscore in override names
BREAKING CHANGE: Overrides that have hyphens will not longer work and must be updated to replace hyphens with underscores.
=> fix: Replace hyphen with underscore in override names

Makefile, bootstrap/handlers/httpserver.go, bootstrap/registration/registry.go, bootstrap/registration/registry_test.go, config/types.go
ServiceInfo struct not used directly by all the services. Some field names a bit ambiguous 
ServiceInfo struct not usable by all the services with better names for some fields. 
BREAKING CHANGE: Service configuration has changed for all services
=> refactor: Update ServiceInfo struct to be used by all services and add MaxRequestSize

bootstrap/secret/secret.go, bootstrap/secret/secret_test.go
Add internal prefix `/v1/secret/edgex/` for secret's Path in `SecretStore` config so that now we only need to specify the service specific secret path instead of the full path with /v1/secret/edgex/ + serviceSecrets
Closes: #249
- [x ] Tests for the changes have been added (for bug fixes / features)
Currently the `Path` specified in the `SecretStore` config is full path with /v1/secret/edgex/ prefixed in all services using secret store.
The fixed prefix `/v1/secret/edgex/` now …
=> refactor!: Add internal prefix for secret path on SecretStore config

bootstrap/secret/secret.go, config/types.go, go.mod
Once retry cleanup code is used, the related configuration items of `AdditionalRetryAttempts`, `RetryWaitPeriod`, and `RetryWaitPeriodTime` for `SecretStore` config struct needs to be removed too.
Fixes: #247
Retry properties still in SecretStore config
Retry properties in SecretStore config struct got removed.
- [x ] Yes
The caller or the client side uses this module will need to clean up these items `AdditionalRetryAttempts`, `RetryWaitPeriod`, and `RetryWaitPeriodTime` in …
=> fix(secuirty): Remove retry config items from SecretStore config

bootstrap/container/common.go, bootstrap/container/data.go, bootstrap/container/deviceservice.go, bootstrap/container/metadata.go, bootstrap/registration/registry.go, config/types.go, go.mod
Files under v2 package moved to existing `container` package
closes 
Using old versions of go-mods which Core Contracts that has `v1` code and `v2` code under the `v2` package
Using latest versions of go-mods which Core Contracts that has no `v2` package or old `v1` code
=> refactor: Update to latest Core Contracts and remove v2 package

bootstrap/environment/variables.go
Logging for EDGEX_CONF_DIR override uses incorrect name `envFile`
Logging for EDGEX_CONF_DIR override uses correct name `envConfDir`
=> fix: Use correct name when logging EDGEX_CONF_DIR override

bootstrap/handlers/httpserver.go
Close: #268
Http server close the conn when request timeout and didn't return any useful message.
Since we can use timeout handler to provide more meaningful error message, we need to remove the timeout settings from the Http server to make the timeout handler works.
=> feat: Use Http Request timeout handler 

bootstrap/secret/secret.go, bootstrap/secret/secure.go, bootstrap/secret/secure_test.go, bootstrap/secret/types.go, bootstrap/secret/types_test.go, config/types.go, go.mod
Secrets are seeded from a JSON file specified by the SecretStore.SecretsFile setting
If SecretsFile setting is blank, seeding is skipped.
closes #273
This PR depends on https://github.com/edgexfoundry/go-mod-secrets/pull/126 to be merged first.
https://github.com/edgexfoundry/edgex-docs/pull/587
1. Start edgex using compose builder `make run ds-camera`
- This will create the `SecretStore` for device camera
2. Stop the Device Camera container
1. Clone branch for this PR and branch for go-mod-secrets PR  https://github.com/edgexfoundry/go-mod-secrets/pull/126
2. Add the following to device-sdk-go `go.mod`
```
replace (
github.com/edgexfoundry/go-mod-bootstrap/v2 => ../go-mod-bootstrap
)
```
3. Add following the device-camera-go …
=> feat: Add optional capability to seed service secrets

bootstrap/handlers/httpcors.go, bootstrap/handlers/httpcors_test.go, bootstrap/handlers/httpserver.go
Modify CORS process middleware and implement preflight handling to meet:
https://www.html5rocks.com/en/tutorials/cors//#toc-cors-server-flowchart
Signed-off-by: Cloud Tsai <cloudxxx8@gmail.com>
Test normal request:
1. Set configuration `EnableCORS = true`, and start an EdgeX service
2. Send a http request with a header `Origin`
3. Very the response header contains `Access-Control-Expose-Headers`, `Access-Control-Allow-Origin`, `Access-Control-Allow-Credentials` with the values the same as the `Service.CORSConfiguration` …
=> fix: Correct the CORS handler logic

.golangci.yml, Makefile, bootstrap/bootstrap.go, bootstrap/messaging/messaging_test.go, bootstrap/secret/secret_test.go, bootstrap/secret/secure.go, bootstrap/secret/secure_test.go, bootstrap/secret/types_test.go
Ran edgex-go using local go-mod-bootstrap in both security and no-secty to make sure everything came up and no errors in logs
N/A
=> feat: Added "make lint" target and added to "make test" target 

bootstrap/config/config.go
fixes #299
Use this branch in App SDK's app template
Run Edgex non-secure stack
Build App template on **Windows**
Run app template with -cp option on **Windows**
Verify Consul contains the configuration at `http://localhost:8500/ui/dc1/kv/edgex/appservices/2.0/new-app-service/`
Via Consul, remove configuration at `http://localhost:8500/ui/dc1/kv/edgex/appservices/2.0/new-app-service/`
Build App template on **Linux**
Run app template with -cp option on **Linux**
Verify Consul …
=> fix: Generate proper Consul base path on Windows

bootstrap/handlers/metrics.go, bootstrap/metrics/manager.go, bootstrap/metrics/reporter.go, bootstrap/metrics/reporter_test.go
For this to work for App Services the Metrics Reporter must get the
Messaging Client from the DIC the first time Report() is called.
Also added locking around the Read/Write of tags maps
Start non-secure stack and stop Core Data container
Use this branch in edgex-go 
Build Core Data
Change to Telemetry config to enable both metrics and debug logging
Verify logs have the following every 30sec
```
level=DEBUG ts=2022-04-19T21:58:24.6701809Z app=core-data …
```
=> refactor: Rework how Metrics Reporter gets the Messaging Client

bootstrap/handlers/httpserver.go, bootstrap/handlers/httpserver_test.go, config/types.go
fixes edgexfoundry/edgex-go#3612
Signed-off-by: Ginny Guan <ginny@iotechsys.com>
1. build services from this branch and set the MaxRequestSize config to 1
2. send POST request with a request body over 1KB
3. verify the responses, for example,
```
curl -ki -X POST http://localhost:59881/api/v2/deviceprofile/uploadfile -F "file=@./test-profile.yml"
HTTP/1.1 413 Request Entity Too Large
Content-Type: application/json
Date: Tue, 19 Apr 2022 01:45:10 GMT
Content-Length: 98
Connection: close …
```
=> feat: Add RequestLimitMiddleware for Service.MaxRequestSize config

config/types.go, config/types_test.go
This allows for a class of Metrics to be enabled with one configured
metric name. App SDK uses this for PipelineMetrics by appending the
pipeline ID to the name of the metric(s) it is collecting for multiple
function pipelines.
Run non-secure EdgeX stack and stop Core Data container
Use this branch to build Core Data locally
Change Metric config to enable both metrics
Run with DEBUG logging and verify 2 metrics are reported.
=> feat: Enhance metric name matching to match on prefix

bootstrap/config/config.go, bootstrap/handlers/metrics.go, bootstrap/metrics/manager_test.go
**TBD**
use branch in Core Data
Build and run Core Data from command line with DEBIG logging
Set interval to 0
Verify logs have following:
```
0 specified for metrics reporting interval. Setting to max duration to effectively disable reporting.
```
=> feat: Add ability to disable metric reporting with interval of 0

bootstrap/metrics/reporter.go, config/types.go, config/types_test.go
This allows the common metrics controlled by name to be reported as a
single metric. The service must add a Tag to the individual metrics
collected so the data can be seprated.
TBD
Build App Template with module from this branch
Run from command line with DEBUG logging and verify 8 metrics being reported.
Run ASC with metrics-influxdb using the following command
```
./app-service-configurable -p=metrics-influxdb | grep "Transformed Metric to"
```
Verify logs contain metrics with …
=> refactor: Rework metric name reported to be the name from configuration

bootstrap/messaging/messaging.go
Put CA cert into MessageBusInfo for all auth modes if it is present in the Secret Data.
fix: #323 
Signed-off-by: Felix Ting <felix@iotechsys.com>
=> feat: Put CA cert into MessageBusInfo for all AuthModes

bootstrap/bootstrap.go, bootstrap/config/config.go
fixes #314 for Jakarta
Backport of this PR: https://github.com/edgexfoundry/go-mod-bootstrap/pull/315
Use PR branch in Jakarta version of APP SDK
Build App Template.
Start app w/o override of `APPCUSTOM_SOMEVALUE`
Restart app with override of `APPCUSTOM_SOMEVALUE=999`
Verify logs DO NOT contain message about AppCustom.SomeValue has changed to 123
=> fix(config): (jakarta) ignore first change notification for custom config

bootstrap/bootstrap.go, bootstrap/handlers/httpserver.go
fixes #318
Use this branch in device SDK and Device Rest
Run Device Rest
Press control C
Verify  `echo $?` returns 0
Run Device Rest
Run Device Rest in another terminal
Verify if fails due to port bind error
Verify  `echo $?` returns 1
=> fix: Ensure exit with non-zero code when error occurs

bootstrap/handlers/messaging.go, bootstrap/handlers/messaging_test.go, config/types.go
This is needed as other core/support service start using the MessageBus
for Service Metrics and System Events.
Use this branch in edgex-go
Modify core -data to:
- Use new handler from this branch
- Add setting MessageQueue in result returned by GetBootstrap()
- Build an run Core Data.
- Verify runs fine and receives data from the MessageBus
=> feat: Add common Messaging bootstrap handler

bootstrap/config/config.go
fixes #361.
Run WatchForChange in a new thread to receive the error chan.
Signed-off-by: Lindsey Cheng <beckysocute@gmail.com>
=> fix: Run WatchForChange in a new thread

bootstrap/container/externalmqtt.go, bootstrap/handlers/externalmqtt.go, bootstrap/handlers/messaging.go, config/types.go, go.mod, go.sum
to support north-south messaging implementation for internal and
external MessageBus connection
Signed-off-by: Chris Hung <chris@iotechsys.com>
https://github.com/eclipse/paho.mqtt.golang
used by app-functions-sdk-go to connect to external MQTT broker.
We extract the logic here so that it can be reused by north-south messaging implementation and app-sdk in the future.
=> feat: add new 'Topics' field and external MQTT BootstrapHandler

bootstrap/environment/variables.go, bootstrap/environment/variables_test.go
Signed-off-by: Anthony Casagrande <anthony.j.casagrande@intel.com>
Closes #366 
tested using `go.mod`:
```
replace (
github.com/edgexfoundry/go-mod-bootstrap/v2 => ../go-mod-bootstrap
)
```
Output:
```
level=INFO ts=2022-09-01T18:52:41.98712185Z app=device-onvif-camera source=config.go:391 msg="Loaded service configuration from ./res/configuration.toml"
level=INFO ts=2022-09-01T18:52:41.987407499Z app=device-onvif-camera source=variables.go:371 msg="Variables override of 'Writable.LogLevel' by environment variable: …
```
=> feat: redact logging of insecure secrets env override

bootstrap/bootstrap.go, bootstrap/interfaces/mocks/SecretProvider.go, bootstrap/interfaces/secret.go, bootstrap/secret/insecure.go, bootstrap/secret/secure.go
applies to #374
TBD
Run non-secure EdgeX stack
Run ACS with metrics-influxdb profile from command line with DEBUG logging
```
WRITABLE_LOGLEVEL=DEBUG EDGEX_SECURITY_SECRET_STORE=false ./app-service-configurable -p=metrics-influxdb | grep Transformed Metric
```
Build and run app template in App SDk with go-mod-bootstrap from this branch
Disable all exiting metrics in the app template config file
Add the following metrics enabled
```toml
[Writable.Telemetry.Metrics] # All service's …
```
=> feat: Add service metrics for Secrets requested and stored

bootstrap/environment/variables.go, bootstrap/environment/variables_test.go
fixes #375
TBD
Build Core Data using go-mod-bootstrap from this branch
Run non-secure EdgeX Stack
Stop Core Data and remove Core Data config from Consul
Run Core Data from command-line using:
```
EDGEX_CONFIGURATION_PROVIDER=none ./core-data -cp
```
Verify logs show override
```
"Variables override of 'Configuration Provider Information' by environment variable: EDGEX_CONFIGURATION_PROVIDER=none"
```
Verify logs don't mention use of config provider
Run Core Data from command-line …
=> fix: Add capability to override config provider settings with "none"

bootstrap/config/config.go
BREAKING CHANGE: Service configuration location in Consul has changed
Version is now in the default config stem
closes #400
Note: this PR is dependent on  https://github.com/edgexfoundry/go-mod-core-contracts/pull/776 being merged first.
=> refactor!: Don't add version to Config Stem

bootstrap/config/provider_test.go, bootstrap/environment/variables.go, bootstrap/environment/variables_test.go
resolve #399 
BREAKING CHANGE:
- `EDGEX_CONFIGURTION_PROVIDER` is replaced by `EDGEX_CONFIG_PROVIDER`
- `EDGEX_CONF_DIR` is replaced by `EDGEX_CONFIG_DIR`
Signed-off-by: Felix Ting <felix@iotechsys.com>
1. Download this docker-compose file(https://github.com/edgexfoundry/edgex-compose/blob/main/docker-compose-no-secty.yml) and edit it to remove device-virtual
2. Run EdgeX Foundry with the docker-compose file
3. Download https://github.com/FelixTing/go-mod-bootstrap/tree/issue-399
4. Download device-virtual …
=> feat: Rename environment variables for the sake of consistency

bootstrap/config/config.go, bootstrap/environment/variables.go, bootstrap/environment/variables_test.go, bootstrap/flags/flags.go, bootstrap/flags/flags_test.go
BREAKING CHANGE:
- `-c/--confdir` to `-cd/--configDir`
- `-f/--file` to `-cf/--configFile`
Signed-off-by: Felix Ting <felix@iotechsys.com>
Signed-off-by: Ginny Guan <ginny@iotechsys.com>
related issue: https://github.com/edgexfoundry/edgex-go/issues/4248
Run core-data with `-cd/--configDir` and `-cf/--configFile`
=> refactor!: Rename command line flags for the sake of consistency

bootstrap/handlers/messaging.go, bootstrap/handlers/messaging_test.go, config/types.go
BREAKING CHANGE: MessageQueue renamed to MessageBus and fields changed. See v3 Migration guide.
TBD
See follow on PRs for edgex-go
=> refactor!: Rework MessageBus configuration for all services to use consistently

bootstrap/bootstrap.go, bootstrap/config/config.go, bootstrap/environment/variables_test.go, bootstrap/handlers/externalmqtt.go, bootstrap/secret/insecure_test.go, bootstrap/secret/secret.go, bootstrap/secret/secret_test.go, bootstrap/secret/secure.go, bootstrap/secret/secure_test.go, config/types.go
BREAKING CHANGE: SecretStore config no longer in service configuration file. Changes must be done via use of environment variable overrides of default values
TBD
Build core data with this branch
Run secure EdgeX stack, store core data container and remove core data config from Consul
Run core data locally with DEBUG logging and SecretStore enabled.
```
sudo EDGEX_SECURITY_SECRET_STORE=true WRITABLE_LOGLEVEL=DEBUG ./core-data -cp -r
```
Verify core data bootstraps successfully and …
=> refactor!: Replace SecretStore service config with default values and overrides

bootstrap/config/config.go
Signed-off-by: Elizabeth J Lee <elizabeth.j.lee@intel.com>
=> refactor: move configuration location code to public helper function

bootstrap/bootstrap.go, bootstrap/config/config.go, bootstrap/config/config_test.go, bootstrap/config/configmock_test.go, config/types.go, go.mod
BREAKING CHANGE: calls to bootstrap.RunAndReturnWaitGroup must include the service type
Signed-off-by: Elizabeth J Lee <elizabeth.j.lee@intel.com>
**Non-secure mode testing**
1. set the environment variable for non-secure testing `export EDGEX_SECURITY_SECRET_STORE=false`
2. run the latest compose builder `make run no-secty` to start core services
3. stop core data
4. remove the core data configuration in consul
5. modify local go-mod in edgex-go to use local bootstrap using `replace` statement
6. modify the …
=> feat!: load common configuration

bootstrap/config/config.go
Signed-off-by: Elizabeth J Lee <elizabeth.j.lee@intel.com>
1. start compose stack in non-secure mode
2. point device-sdk device simple to the local bootstrap
3. build device simple and run with config provider
4. change the writable loglevel and ensure the log level changes
=> fix: move listen for changes for private config to run on startup

bootstrap/config/config.go, bootstrap/config/config_test.go
1. run edgex stack in non-secure mode
2. stop core data and remove core-data from config provider
3. modify edgex-go/go.mod to use local bootstrap
4. run core-data with config provider
5. verify core data is in the config provider
=> fix: retry logic for checking if common config is ready

bootstrap/handlers/auth_middleware.go, bootstrap/handlers/clients.go, bootstrap/interfaces/mocks/SecretProvider.go, bootstrap/interfaces/secret.go, bootstrap/secret/insecure.go, bootstrap/secret/insecure_test.go, bootstrap/secret/jwtprovider.go, bootstrap/secret/secure.go, bootstrap/secret/secure_test.go, di/container.go, go.mod, go.sum
This commit consumes the breaking change to go-mod-core-contracts
by injecting a Vault-issued JWT into all outgoing HTTP requests.
This commit presumes changes to security-secrestore-setup
to initialize Vault service identity and go-mod-secrets interface
changes to request and validate JWTs.  Adopting this change does
not force authentication on inbound requests, as authentication
must be enabled on a route-by-route basis in each EdgeX microservice.
Signed-off-by: Bryon Nevis <bryon.nevis@intel.com>
`make test`
=> feat: Add go-mod-bootstrap hooks for JWT generation and verification

bootstrap/handlers/httpserver.go
Discovered this error when the code got called with RequestTimeout="" and it couldn't be parsed as a duration.  Have not extensively tested the fix.
=> fix: Don't attempt to wrap error to LoggingClient

bootstrap/handlers/auth_middleware.go
Authentication tracing was very chatty, which was useful during development.
Now that the feature is merged, authentication attempts are now logged at DEBUG level,
as well as authorization success.  Authorization failures are now logged as WARNING.
`make test` to ensure no breakage.
otherwise no major functional impact of these changes.
=> fix: Authentication status is now DEBUG, auth failure is WARN

bootstrap/config/config.go, bootstrap/environment/variables.go
BREAKING CHANGE: Overrides are no longer applied to values pulled from Configuration Provider. Configuration Provideris now the system or record for configuration, when used.
closes #482
Run non-secure EdgeX stack
Stop Core Data container.
Remove Core Data config from Consul
Build Core Data using go-mod-bootstrap from this branch
run `export WRITABLE_LOGLEVEL=DEBUG`
Run core data from command-line with `-cp`
Verify logs contain the following:
```
"Using Configuration provider (consul) from: http://localhost:8500 with …
```
=> feat!: Apply env overrides only when config loaded from file

bootstrap/config/config.go, bootstrap/flags/flags.go
BREAKING CHANGE: All configruation file must now be in YAML format. The default file name has changed to be configuration.yaml
closes #424
run non-secure EdgeX stack
Stope core data and remove core data config from Consul
Build core data with this branch
Convert core data config to YAML
Run core data from command line with just -cp
Verify core data config loaded and pushed to consul
=> refactor!: Switch to loading configuation files as YAML

bootstrap/config/config.go, bootstrap/config/config_test.go, bootstrap/config/testdata/all-service-config.yaml, bootstrap/config/testdata/configuration.yaml, bootstrap/environment/variables.go, bootstrap/environment/variables_test.go, bootstrap/flags/flags.go, bootstrap/flags/flags_test.go, go.mod
[docs PR](https://github.com/edgexfoundry/edgex-docs/pull/990)
**Non-secure mode testing **
1. set the environment variable for non-secure testing `export EDGEX_SECURITY_SECRET_STORE=false`
2. run the latest compose builder `make run no-secty` to start core services
3. stop core data
4. remove the core data configuration in consul
5. modify local go-mod in edgex-go to use bootstrap from [this branch](https://github.com/ejlee3/go-mod-bootstrap/tree/common-config-flag)
7. build core data `make data`
9. run core-data locally and ensure that …
=> feat: Add command line/environment flag for commonConfig

config/types.go
BREAKING CHANGE: Database Timeout type has changed from `int` to `string`
closes #499
Build core-data with this branch
Run core-data and verify it successfully connects to the Database
```
"Database for V2 API connected"
```
=> refactor!: Change Database timeout to a duration string

bootstrap/config/config.go, bootstrap/config/config_test.go, bootstrap/utils/utils.go, bootstrap/utils/utils_test.go
fixes #501
Build Core Data/ App Template/ Device Simple with this branch
Run each and verify the following
- Configs are loaded from file and pushed to Config Provider as expected
-   - Common configs and private configs merged without losing empty setting in private config
- Configs are loaded from Config Provider as expected
- Common configs and private configs merged without losing empty setting in private config
- Writable changes are handled at all levels 
- Private
- All Common
- App or Device common
=> fix: Rework merge of configs to better handle empty values

bootstrap/bootstrap.go, bootstrap/config/config.go, bootstrap/container/secret.go, bootstrap/handlers/auth_middleware.go, bootstrap/handlers/clients.go, bootstrap/interfaces/secret.go, bootstrap/registration/registry.go, bootstrap/secret/jwtprovider.go, bootstrap/secret/secret.go, bootstrap/secret/secret_test.go
BREAKING CHANGE: Service that need full SecretProvider API now use SecretProviderExt. Extra APIs have been removed for App/Device Services.
closes #398
https://github.com/edgexfoundry/edgex-docs/pull/1020
See https://github.com/edgexfoundry/edgex-go/pull/4510 testing
=> refactor!: Rework SecretProvider interface so App/Device Services have limited API

bootstrap/config/config.go, bootstrap/config/configmock_test.go, bootstrap/flags/flags.go, bootstrap/handlers/clients.go, bootstrap/handlers/clients_test.go, bootstrap/handlers/messaging.go, bootstrap/handlers/messaging_test.go, bootstrap/handlers/metrics_test.go, bootstrap/registration/registry_test.go, config/types.go
Dev Mode is used when running service locally with the other services running in Docker (aka hybrid mode). This causes all the `Host` settings pulled from common configuration to be overridden with the value `localhost`.
closes #509
TBD
Use in edgex-go, app sdk and device sdk and make appropriate code changes
Build and run core/support services with "-cp -d" options with other services running in docker
Verify service bootstraps properly
Build and run device-simple with "-cp -d" options with other services running in docker
Verify …
=> feat: Add -d/--dev common command-line flag to put service in Dev Mode

bootstrap/config/config.go, bootstrap/utils/utils.go, bootstrap/utils/utils_test.go
fixes #524
- [n/a?] I have opened a PR for the related docs change (if not, why?)
N/A due to no functionality change
- Run EdgeX in non-secure mode
- Run a service with a secret callback code
- Change an InsecureSecret
- Verify that the callback was triggered
=> fix: InsecureSecrets change detection

bootstrap/config/config.go, bootstrap/config/config_test.go
fixes #503
Run EdgeX non-secure stack
In Consol, create an App services common  override of Metrics.Interval with `45s`
Use this branch in App SDK to build App Template
Run `./app-new-service -cp -d`
Verify in the logs the Metrics manager Interval is `45s` (is. not the default `30s` in the all-services common
From Consul change the Metrics.Interval in all-services common to `5m`
Verify the app service log shows following message:
```
"ignoring changed writable key Telemetry/Interval overwritten in App or Device common …
```
=> fix: [WIP BUG] Ignore Common Writable changes overridden in App/Device common Writable

bootstrap/handlers/auth_middleware.go, bootstrap/secret/helper.go, bootstrap/secret/secure.go
- [N/A] I have added unit tests for the new feature or bug fix (if not, why?)
- [N/A] I have opened a PR for the related docs change (if not, why?)
- I moved the constant out of `secure.go` as that file is specific for the vault/secure implementation. It remains in the same package `secret`.
- Invalid log spotted while debugging (note the `%s` on the last line):
=> fix: incorrect call to log.Debug, move WildcardName constant

bootstrap/secret/secret.go, bootstrap/secret/secure.go
Closes: #374
Run with security on 
1. test with [edgex-go](https://github.com/edgexfoundry/edgex-go/pull/4556) 
2. run `make clean_docker_base docker_base docker`
3. go to edgex-compose/compose-builder
4. `make run dev delayed-start mqtt-bus`
5. `cat /tmp/edgex/secrets/core-data/secrets-token.json` and copy the client_token
6. `export VAULT_TOKEN=insert_client_token`
7. `docker exec -ti -e VAULT_TOKEN=$VAULT_TOKEN edgex-vault vault kv get secret/edgex/core-data/message-bus` and copy the username and password
8. `docker …
=> feat: add secret token and get secret metrics

bootstrap/config/config.go
fixes #540
Run Clean EdgeX non-secure stack
Use this branch in Device SDK to build Device Simple
Change Service.Host in Device Simple config file to be IP address of current system
Run Device Simple with `-cp -d -o` flags
Verity it starts w/o errors
Send GET request to http://localhost:59882/api/v3/device/name/Simple-Device01/Switch
Verify it returns 200 and an event
=> fix: [WIP] Remove dev override of Service.Host so IP address can be used

bootstrap/metrics/manager.go, bootstrap/metrics/reporter_test.go
**I have only fully tested via the unit tests, and not under a real working scenario**
- checkout current main branch
- run: `go test github.com/edgexfoundry/go-mod-bootstrap/v3/bootstrap/metrics -test.count 10`
- expect `FAIL`
- checkout this PR
- run `go test github.com/edgexfoundry/go-mod-bootstrap/v3/bootstrap/metrics -test.count 10`
- expect `PASS`
I have verified that this Fixes #458 on my local machine
=> fix(metrics): do not use shared DefaultRegistry and fix wg.Done call

bootstrap/config/config.go, bootstrap/config/config_test.go, bootstrap/secret/insecure.go, bootstrap/secret/insecure_test.go, bootstrap/secret/secret.go
Implements the StoreSecret function for InsecureProvider. If the ConfigurationClient is in use, it will be used to store the secret, otherwise an error is returned.
**Run the new unit tests**
```
make test
```
**Try it out yourself**
1. clone latest edgex-compose
2. modify a device service to build using this code
go.mod:
```
replace github.com/edgexfoundry/go-mod-bootstrap/v3 => ../go-mod-bootstrap
```
3. build docker image
```
make docker
```
4. tag image so it is latest:
```
docker tag …
```
=> feat: support /api/v3/secret endpoint in non-secure mode

bootstrap/config/config.go, bootstrap/config/config_test.go, bootstrap/environment/variables.go, bootstrap/environment/variables_test.go, bootstrap/file/file.go, bootstrap/file/file_test.go, bootstrap/flags/flags.go
close #553
- add EDGEX_CONFIG_FILE=<url path to valid config.yaml file> to any service
- start edgex in secure or no-secure mode
- Modified service should get config from the remote location instead of the local copy.
=> feat: Use loadfile that allows reading from local file or uri

bootstrap/handlers/clients.go, bootstrap/handlers/httpserver.go, bootstrap/handlers/messaging.go, bootstrap/registration/registry.go
Gives a better error messages when the developer runs with hybrid mode but not including common config.
Closes: #564
- git clone this PR
- you can use device-simple from device-sdk repo to test this out when running in hybrid mode and don't provide common config (i.e. no -cc flag in place when running it)
- in the device sdk, change the go-mod-bootstrap import to the local cloned go-mod-bootstrap in go.mod file
- run `make` first from the base root of device-sdk repo to compile the device-sdk together with the local …
=> feat: add better error handlings when common config is missing

bootstrap/utils/handler.go, bootstrap/utils/handler_test.go
Closes #575. Add wrapper function to wrap http handler into echo.Handler.
=> feat: Add wrapper func to wrap http handler for Echo

Makefile, bootstrap/handlers/messaging_test.go, bootstrap/messaging/messaging_test.go, go.mod
Also fixed linter errors for `G601: Implicit memory aliasing in for loop.` in unit tests
=> build: Upgrade to go 1.21 and linter 1.54.2

bootstrap/handlers/clients.go, config/types.go, go.mod, go.sum
BREAKING CHANGE: Add EnableNameFieldEscape config on the service level and allow NameFieldEscape configurable
Related PRs are opened, you can refer to https://github.com/edgexfoundry/edgex-go/issues/4673#issuecomment-1709699336 and run services to verify the API.
=> feat!: Add EnableNameFieldEscape config

bootstrap/config/config.go
Run non-secure edgex stack
Build Device SImple (Go Device SDK) with this branch
run Device SImple in Dev Mode (`./device-simple -cp -d -o`)
Verify `Simple-Device01` was added as a device to Core MetaData (via Edgex UI)
Send following command to Core Command
```
curl http://localhost:59882/api/v3/device/name/Simple-Device01/Switch
```
Verify 200 response and a new Event is returned.
=> fix: Expand DevMode flag to set values for external access

bootstrap/handlers/clients.go, bootstrap/handlers/clients_test.go
Using the following branch of the minimal reproduction: https://github.com/jrtitus/edgex-app-reading-client-poc/tree/fix-bootstrap (referencing the commit in this PR)
The result is a non-nil `ReadingClient`:
```
level=INFO ts=2024-02-16T03:37:46.594768Z app=service-key source=service.go:587 msg="Service started in: 49.244084ms"
level=INFO ts=2024-02-16T03:37:46.601778Z app=service-key source=main.go:25 msg="Event Count: 575"
level=INFO ts=2024-02-16T03:37:46.60344Z app=service-key source=main.go:34 msg="Reading Count: …
```
=> fix: bootstrap ReadingClient for core-data

bootstrap/handlers/clients.go, bootstrap/handlers/httpserver.go, bootstrap/zerotrust/zerotrust.go
following https://github.com/edgexfoundry/go-mod-bootstrap/issues/650 and https://github.com/edgexfoundry/go-mod-bootstrap/pull/659, when enabling app-services to be able to participate with the zero trust overlay it's necessary to mark the secret provider if the key zero trust mode is set
=> feat: allow clients to be zero trust

bootstrap/config/config.go, bootstrap/handlers/httpserver.go, bootstrap/zerotrust/zerotrust.go
Adds the ability for a server to get the key passed in as a param. that key is then used to find/bind an OpenZiti service
=> feat: Add service key to HTTP Server

bootstrap/handlers/clients.go, go.mod, go.sum
Add enableNameFieldEscape parameter to CommandClient to enable MessageBus topic path encoding
=> feat: CommandClient can encode MessageBus topic

bootstrap/bootstrap.go, bootstrap/registration/registry.go, go.mod, go.sum
=> feat: Core Keeper changes based on OpenZiti changes

bootstrap/config/config.go, bootstrap/environment/variables.go
Since the flag is hard to use for the container environment, create a new env EDGEX_OVERWRITE_CONFIG to provide the same feature support as -o/--overwrite flag.
Close #747
1. Start the EdgeX with the default configs and config provider.
2. Modify the docker-compose file with the environment variable `EDGEX_OVERWRITE_CONFIG: true` and set other environment variable to change the private or common config.
3. Check the config provider if the new change of the environment variable overwrite is pushed.
=> feat: Add new env to support -o flag

.golangci.yml, Makefile, bootstrap/handlers/httpserver.go, bootstrap/messaging/testcerts_test.go, go.mod
Upgrade to go-1.23, Linter1.61.0
Run `make test`.
=> build: Upgrade to go-1.23, Linter1.61.0

.github/dependabot.yml
Close https://github.com/edgexfoundry/go-mod-bootstrap/issues/781
=> build: Ignore go-mod-messaging from dependabot

bootstrap/handlers/messaging_test.go, config/types.go, go.mod, go.sum
Per https://github.com/edgexfoundry/go-mod-messaging/issues/366, EdgeX remove support on Redis Pub/Sub as message bus, so unit tests related to redis pub/sub should be removed as well to avoid errors.
Note that redis pub/sub doesn't need to establish preemptive connection before publish and subscribe, and a redis client can be susccessfully created and make noop Connect() without error per the implmentation of removed unit tests.
=> fix: remove unit tests related to redis pub/sub

bootstrap/container/clients.go, bootstrap/handlers/clients.go, bootstrap/handlers/clients_test.go
BREAKING CHANGE: the cron scheduler name and key changed
Replace the old Scheduler service with the new cron Scheduler service
fixes https://github.com/edgexfoundry/edgex-go/issues/5002
- [] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
=> refactor: Replace old Scheduler service with cron Scheduler service

bootstrap/container/clients.go, bootstrap/controller/commonapi.go, bootstrap/handlers/auth_func.go, bootstrap/handlers/auth_middleware.go, bootstrap/handlers/auth_middleware_no_ziti.go, bootstrap/handlers/auth_secretstore.go, bootstrap/handlers/constants.go, bootstrap/handlers/headers/jwt.go, bootstrap/handlers/headers/jwt_test.go, bootstrap/handlers/headers/key.go, bootstrap/handlers/headers/key_test.go, go.mod, go.sum
Resolves #810. Enhance the auth middleware func to support external JWT verifcation.
=> feat: Enhance the auth hook func to support external JWT

bootstrap/handlers/auth_middleware.go, bootstrap/handlers/auth_middleware_no_ziti.go, bootstrap/handlers/auth_secretstore.go
Relates to #810. Execute the next handler function properly in auth_middleware.
=> fix: Execute the next handler function in auth_middleware

bootstrap/handlers/clients.go, bootstrap/handlers/clients_test.go
Fixes #815. Add the security-proxy-auth svc client to ClientsBootstrap.
=> fix: Add the security-proxy-auth svc client

bootstrap/config/config.go
- split loadConfigByProvider to a separate method to make if/else statement clearer
- split loadPrivateConfigFromFile to a separate method for reuse in if/else branches
I tried to make some changes for my own purpose. While I read the code although the code works perfectly, it a little bit hard to understand and change because the config loading logic from the provider and file are mixed.  I refactored it to split the loading logic , i.e. loading from provider and file, to 2 methods, which made my changes easier.  Later on I found other solution so the changes got dropped, but I am trying to push the refactor to see if anyone is interested.
If your build fails due to your commit message not passing the build checks, please review the guidelines here: …
=> refactor: try to refactor the load config code to 2 clear pathes

bootstrap/config/config.go, go.mod, go.sum
correctly get configuration provider client to avoid nil panic
=> fix: get updated configuration provider client for config changes

bootstrap/config/config.go
=> fix: retrieve privateConfigClient from dic

bootstrap/config/config.go
After upgrading EdgeX, new configurations may be introduced. Ensure new configurations from the YAML file are pushed to the core-keeper.
- deploy old version (such tag [v4.1.0-dev.46](https://github.com/edgexfoundry/edgex-go/releases/tag/v4.1.0-dev.46)) edgex-go
- shut down and deploy the latest edgex-go with this PR.
- verify the new configs are pushed to core-keeper
=> feat: Ensure new configurations from the file are applied

bootstrap/bootstrap.go, bootstrap/messaging/messaging.go, go.mod, go.sum
fix: #896 
This enables service to wait for MessagingClient critical operations to complete during graceful shutdown.
This depends on https://github.com/edgexfoundry/go-mod-messaging/pull/436
=> feat: Integrate MessagingClient critical operation signaling into shutdown process
